name: server
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17.5'
      - run: go mod tidy && CGO_ENABLED=0 go build -a -o icmpshell-server-linux-amd64 ./cmd/server
      - uses: actions/upload-artifact@v4
        with:
          name: server
          path: icmpshell-server-linux-amd64
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: icmpshell-server-linux-amd64