name: shell
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - run: go mod tidy && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o icmpshell-shell-linux-amd64-Ex ./cmd/shell
      - run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -a -o icmpshell-shell-windows-amd64-Ex.exe ./cmd/shell
      - run: CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -a -o icmpshell-shell-darwin-arm64-Ex ./cmd/shell
      - uses: actions/upload-artifact@v4
        with:
          name: shell
          path: |
            icmpshell-shell-linux-amd64-Ex
            icmpshell-shell-windows-amd64-Ex.exe
            icmpshell-shell-darwin-arm64-Ex
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            icmpshell-shell-linux-amd64-Ex
            icmpshell-shell-windows-amd64-Ex.exe
            icmpshell-shell-darwin-arm64-Ex
